src/Entity/Details.php
<?php

namespace App\Entity;

use App\Repository\DetailsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: DetailsRepository::class)]
class Details
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::BIGINT)]
    private ?string $timestemp = null;

    #[ORM\Column(length: 255)]
    private ?string $level = null;

    #[ORM\Column(length: 255)]
    private ?string $client_ip = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $message = null;

    #[ORM\ManyToOne(inversedBy: 'log')]
    private ?Log $log = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTimestemp(): ?string
    {
        return $this->timestemp;
    }

    public function setTimestemp(string $timestemp): static
    {
        $this->timestemp = $timestemp;

        return $this;
    }

    public function getLevel(): ?string
    {
        return $this->level;
    }

    public function setLevel(string $level): static
    {
        $this->level = $level;

        return $this;
    }

    public function getClientIp(): ?string
    {
        return $this->client_ip;
    }

    public function setClientIp(string $client_ip): static
    {
        $this->client_ip = $client_ip;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): static
    {
        $this->message = $message;

        return $this;
    }

    public function getLog(): ?Log
    {
        return $this->log;
    }

    public function setLog(?Log $log): static
    {
        $this->log = $log;

        return $this;
    }
}

src/Form/DetailsType.php
<?php

namespace App\Form;

use App\Entity\Details;
use App\Entity\Log;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DetailsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('timestemp')
            ->add('level')
            ->add('client_ip')
            ->add('message')
            ->add('log', EntityType::class, [
                'class' => Log::class,
                'choice_label' => 'id',
            ])
        ;
    }

    public function registerDetails(FormBuilderInterface $builder, array $opts, array $details): void
    {
        $builder
            ->add('timestamp')
            ->add('level')
            ->add('client_ip')
            ->add('message')
            ->add('log', EntityType::class, [
                'class'=> Log::class,
                'choice_label' => 'id',
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Details::class,
        ]);
    }
}

src/Controller/DetailsController.php
<?php

namespace App\Controller;

use App\Entity\Details;
use App\Form\DetailsType;
use App\Repository\DetailsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/details')]
class DetailsController extends AbstractController
{
    #[Route('/', name: 'app_details_index', methods: ['GET'])]
    public function index(DetailsRepository $detailsRepository): Response
    {
        return $this->render('details/index.html.twig', [
            'details' => $detailsRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_details_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $detail = new Details();
        $form = $this->createForm(DetailsType::class, $detail);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($detail);
            $entityManager->flush();

            return $this->redirectToRoute('app_details_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('details/new.html.twig', [
            'detail' => $detail,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_details_show', methods: ['GET'])]
    public function show(Details $detail): Response
    {
        return $this->render('details/show.html.twig', [
            'detail' => $detail,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_details_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Details $detail, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(DetailsType::class, $detail);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_details_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('details/edit.html.twig', [
            'detail' => $detail,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_details_delete', methods: ['POST'])]
    public function delete(Request $request, Details $detail, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$detail->getId(), $request->request->get('_token'))) {
            $entityManager->remove($detail);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_details_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/details/_delete_form.html.twig
<form method="post" action="{{ path('app_details_delete', {'id': detail.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ detail.id) }}">
    <button class="btn">Delete</button>
</form>

templates/details/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/details/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Details{% endblock %}

{% block body %}
    <h1>Edit Details</h1>

    {{ include('details/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_details_index') }}">back to list</a>

    {{ include('details/_delete_form.html.twig') }}
{% endblock %}

templates/details/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Details index{% endblock %}

{% block body %}
    <h1>Details index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Timestemp</th>
                <th>Level</th>
                <th>Client_ip</th>
                <th>Message</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for detail in details %}
            <tr>
                <td>{{ detail.id }}</td>
                <td>{{ detail.timestemp }}</td>
                <td>{{ detail.level }}</td>
                <td>{{ detail.clientIp }}</td>
                <td>{{ detail.message }}</td>
                <td>
                    <a href="{{ path('app_details_show', {'id': detail.id}) }}">show</a>
                    <a href="{{ path('app_details_edit', {'id': detail.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_details_new') }}">Create new</a>
{% endblock %}

templates/details/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Details{% endblock %}

{% block body %}
    <h1>Create new Details</h1>

    {{ include('details/_form.html.twig') }}

    <a href="{{ path('app_details_index') }}">back to list</a>
{% endblock %}

templates/details/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Details{% endblock %}

{% block body %}
    <h1>Details</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ detail.id }}</td>
            </tr>
            <tr>
                <th>Timestemp</th>
                <td>{{ detail.timestemp }}</td>
            </tr>
            <tr>
                <th>Level</th>
                <td>{{ detail.level }}</td>
            </tr>
            <tr>
                <th>Client_ip</th>
                <td>{{ detail.clientIp }}</td>
            </tr>
            <tr>
                <th>Message</th>
                <td>{{ detail.message }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_details_index') }}">back to list</a>

    <a href="{{ path('app_details_edit', {'id': detail.id}) }}">edit</a>

    {{ include('details/_delete_form.html.twig') }}
{% endblock %}